### ISSUE TITLE
ValueError: too many values to unpack (expected 2) 

### ISSUE THREAD

**Issue by Ezra-H** [layumi/Person-reID-triplet-loss#10]
Traceback (most recent call last):                                                                                        
File "train_new.py", line 419, in <module>                                                                         
num_epochs=70)                                                                                                        
File "train_new.py", line 204, in train_model                                                                      
outputs, f = model(inputs)                                                                                          
ValueError: too many values to unpack (expected 2) 

Hello！Thanks for your excellent code！But I met this problem when I wanted to use PCB，I find PCB 
 in model.py return only one value，is  there  something  wrong？Thank you very much！

**Comment by Ezra-H** [comment]
File "test.py", line 119, in extract_feature                                                                   
outputs,f = model(input_img)                                                                                          
File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__                       result = self.forward(*input, **kwargs)                                                                               
File "./model.py", line 81, in forward                        
x,f = self.classifier(x)                                                                                            
ValueError: too many values to unpack (expected 2)

The same problem occured again when I wanted to use "test.py",could you please tell me how to solve it?

**Comment by layumi** [comment]
Hi @Ezra-H 
I did not enable the `PCB` for this triplet code.
I just modify the baseline code.

**Comment by Ezra-H** [comment]
Thank you very much!The problem 2 was solved just now,thanks!
